### ISSUE TITLE
Empty XObject resources cause AttributeError

### ISSUE THREAD

**Issue by maxpmaxp** [maxpmaxp/pdfreader#27]
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/maxp/PycharmProjects/pdfreader/pdfreader/viewer/pdfviewer.py", line 82, in render
    self.notify(obj)
  File "/Users/maxp/PycharmProjects/pdfreader/pdfreader/viewer/pdfviewer.py", line 73, in notify
    handler(obj)
  File "/Users/maxp/PycharmProjects/pdfreader/pdfreader/viewer/simple.py", line 207, in on_Do
    resources_stack=[xobj.Resources])
  File "/Users/maxp/PycharmProjects/pdfreader/pdfreader/viewer/resources.py", line 42, in from_page
    for entry, dict_or_array in res.items():
AttributeError: 'NoneType' object has no attribute 'items'

```

[response-0-6.pdf](https://github.com/maxpmaxp/pdfreader/files/4047410/response-0-6.pdf)

**Comment by maxpmaxp** [comment]
fixed on 0.1.4rc1
