### ISSUE TITLE
ValueError: BT operator without enclosing ET

### ISSUE THREAD

**Issue by i0nathan** [maxpmaxp/pdfreader#62]
>>> viewer.render()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/i0/.pyenv/versions/pdfreader/lib/python3.9/site-packages/pdfreader/viewer/pdfviewer.py", line 119, in render
    self.notify(obj)
  File "/home/i0/.pyenv/versions/pdfreader/lib/python3.9/site-packages/pdfreader/viewer/pdfviewer.py", line 110, in notify
    handler(obj)
  File "/home/i0/.pyenv/versions/pdfreader/lib/python3.9/site-packages/pdfreader/viewer/simple.py", line 112, in on_BT
    raise ValueError("BT operator without enclosing ET")
ValueError: BT operator without enclosing ET

**Comment by maxpmaxp** [comment]
@i0nathan Can you attach your PDF please?

**Comment by maxpmaxp** [comment]
@i0nathan any updates? and you attach you PDF please?

**Comment by i0nathan** [comment]
Hello,
I can't upload the PDF since contains sensitive info, is there any other approach we can take?

Thanks

**Comment by maxpmaxp** [comment]
@i0nathan Can you set a breakpoint at `pdfreader/viewer/simple.py`, line 112 and dump
 - `self.bracket_commands_stack`
 - `self.stream` (dump it to a file if its too long)

**Comment by maxpmaxp** [comment]
@i0nathan any updates?

**Comment by maxpmaxp** [comment]
Added a work around on #119
